apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  # db
  - base/pvc.yaml
  - base/deployment-db.yaml
  - base/service-db.yaml
  # app
  - base/deployment.yaml
  - base/service.yaml
  - base/hpa.yaml