apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: shorturl
    env: base
  name: shorturl
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shorturl
    env: base
  name: shorturl
  namespace: shorturl
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: shorturl
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shorturl
    env: base
  name: shorturl
  namespace: shorturl
spec:
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
        env: base
    spec:
      containers:
      - image: shorturl:v0.0.1
        name: shorturl
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: shorturl
    env: base
  name: shorturl
  namespace: shorturl
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shorturl
  targetCPUUtilizationPercentage: 70
