apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: shorturl
  labels:
    app: db
    env: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        env: base
    spec:
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "db"
          ports:
            - containerPort: 5432
          
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - root
                - -d
                - db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - root
                - -d
                - db
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data