apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: shorturl
  labels:
    app: db
    env: base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
