apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: shorturl
  labels:
    app: db
    env: base
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
