apiVersion: v1
kind: Service
metadata:
  name: shorturl
  namespace: shorturl
  labels:
    app: shorturl
    env: base
spec:
  type: ClusterIP
  selector:
    app: shorturl
  ports:
    - port: 8080
      targetPort: 8080